# -*- coding: utf-8 -*-
"""AthleticsAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNtVejBi4rOZgJVL55ymzFHM5xyy9wI4
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_excel('/content/drive/MyDrive/2025 - 2026/Independent Studies/Data Analysis/Athletics/michaelwesoloski - athlete_events.xlsx')

df

import matplotlib.pyplot as plt
import pandas as pd

# Sample athlete dataset (replace this with your actual dataset)
data = {
    'ID': [1, 2, 3, 4, 5],
    'Age': [25, 28, 23, 30, 26],
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Create a box plot for the distribution of athlete ages
plt.figure(figsize=(8, 6))  # Optional: Adjust the figure size
plt.boxplot(df['Age'], vert=False)
plt.xlabel('Age')
plt.title('Distribution of Athlete Ages')

# Show the plot
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Sample athlete dataset (replace this with your actual dataset)
data = {
    'ID': [1, 2, 3, 4, 5],
    'Weight': [75, 60, 70, 55, 85],
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Calculate the average weight
average_weight = df['Weight'].mean()

# Create a histogram for the average weight
plt.hist(average_weight, bins=10, edgecolor='k')
plt.xlabel('Average Weight')
plt.ylabel('Frequency')
plt.title(f'Histogram of Average Weight (Mean: {average_weight:.2f})')

# Show the histogram
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Sample athlete dataset (replace this with your actual dataset)
data = {
    'ID': [1, 2, 3, 4, 5],
    'Sex': ['M', 'F', 'M', 'F', 'M'],
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Count the number of athletes by gender
gender_counts = df['Sex'].value_counts()

# Create a bar chart to visualize the counts
plt.bar(gender_counts.index, gender_counts.values, color=['blue', 'pink'])
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Number of Athletes by Gender')

# Show the bar chart
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Sample athlete dataset (replace this with your actual dataset)
data = {
    'ID': [1, 2, 3, 4, 5],
    'Medal': ['Gold', 'Silver', 'Bronze', 'Silver', None],
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Count the number of medals in each category
medal_counts = df['Medal'].value_counts()

# Create a pie chart to visualize the distribution of medals
plt.pie(medal_counts, labels=medal_counts.index, autopct='%1.1f%%', startangle=90)
plt.axis('equal')  # Equal aspect ratio ensures that the pie chart is circular.
plt.title('Distribution of Medals Among Athletes')

# Show the pie chart
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Sample athlete dataset (replace this with your actual dataset)
data = {
    'ID': [1, 2, 3, 4, 5],
    'Year': [2018, 2019, 2020, 2021, 2022],
    'Age': [25, 28, 23, 30, 26],
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Create a line plot to visualize the trend of athlete ages over five years
plt.plot(df['Year'], df['Age'], marker='o', linestyle='-')
plt.xlabel('Year')
plt.ylabel('Age')
plt.title('Trend of Athlete Ages Over Five Years')
plt.grid(True)

# Show the line plot
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Sample athlete dataset (replace this with your actual dataset)
data = {
    'ID': [1, 2, 3, 4, 5],
    'Height': [180, 165, 175, 160, 190],
    'Weight': [75, 60, 70, 55, 85],
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Create a scatter plot to visualize the relationship between height and weight
plt.scatter(df['Height'], df['Weight'], c='blue', marker='o')
plt.xlabel('Height')
plt.ylabel('Weight')
plt.title('Relationship Between Height and Weight of Athletes')

# Show the scatter plot
plt.grid(True)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Sample athlete dataset (replace this with your actual dataset)
data = {
    'ID': [1, 2, 3, 4, 5],
    'Weight': [75, 60, 70, 55, 85],
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Calculate the average weight
average_weight = df['Weight'].mean()

# Create a histogram for the weight column using Seaborn
sns.histplot(df['Weight'], bins=10, kde=True)
plt.xlabel('Weight')
plt.ylabel('Frequency')
plt.title(f'Histogram of Weight (Mean: {average_weight:.2f})')

# Show the histogram
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Sample data (replace with your own)
data = {
    'City': ['Tokyo', 'Paris', 'Los Angeles', 'Rio', 'London'],
    'Medals': [33, 24, 23, 19, 27]
}

# Create a DataFrame from the sample data
df = pd.DataFrame(data)

# Create a bar plot using Seaborn
sns.barplot(x='City', y='Medals', data=df)
plt.xlabel('City')
plt.ylabel('Number of Medals')
plt.title('Number of Medals in Different Cities')

# Rotate the x-axis labels for better readability
plt.xticks(rotation=45)

# Show the plot
plt.show()