# -*- coding: utf-8 -*-
"""Global_Sustainability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ioWMy-T1017vo99t7vXzyRb5zk7skYqj
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/2025 - 2026/Independent Studies/Data Analysis/Global Sustainability/global-data-on-sustainable-energy.csv')

from google.colab import drive
drive.mount('/content/drive')

"""##Questions:
1. Identify the relationship between the Renewable Energy Share and GDP per capita over time for countries in different income categories.
2. Show the first 5 rows of data for countries with the greatest decline in Carbon Dioxide Emissions (metric tons per capita) between 2005 and 2015.
3. Can you identify countries that have effectively disengaged economic growth from carbon emissions?
4. Examine the influence of Financial Flows to Developing Countries (US $) on the Renewable-Electricity-Generating-Capacity-Per-Capita for nations with varying levels of GDP per capita.
5. can you generate a time-series line chart depicting the annual change in Carbon Dioxide Emissions (metric tons per capita) for the region with highest emmisions?

"""

df

df.dtypes

df.isna().sum()

df.shape



"""##Question 1"""

df['gdp_per_capita'].sort_values(ascending = False) #3,367 / 3 = 1,122.333333 or 1,123

df.columns

gdpSorted = df['gdp_per_capita'].sort_values(ascending = False)

v = gdpSorted.iloc[1123]

v

df['gdp_per_capita'].sort_values(ascending = False).head(20)

df['gdpSorted'].head(20)

df['High GDP'] = df.iloc[:1123, 21]

df['Mid GDP'] = df.iloc[1124:2246, 21]

df['Low GDP'] = df.iloc[2247:3367, 21]

k = 0
while ~(k==3367):
  if(df['gdp_per_capita']>9547.852151):

df.head(10)

df.loc[:,('Renewable energy share in the total final energy consumption (%)','High GDP', 'Mid GDP', 'Low GDP')]



"""##Question 2

Show the first 5 rows of data for countries with the greatest decline in Carbon Dioxide Emissions (metric tons per capita) between 2005 and 2015.
"""

df

df.columns

df[(df['Year']>=2005) & (df['Year']<=2015)]

filtered_df = df[df['Year'].isin([2005, 2015])]

filtered_df = filtered_df[['Entity', 'Year', 'Value_co2_emissions_kt_by_country']]

agg_df = filtered_df.groupby(['Entity', 'Year'])['Value_co2_emissions_kt_by_country'].sum().unstack().reset_index()

agg_df['Change_in_CO2_emissions_kt'] = agg_df[2015] - agg_df[2005]

agg_df = agg_df.sort_values(by='Change_in_CO2_emissions_kt', ascending=True)

agg_df['Entity'].head(5)

"""##Question 3

Can you identify countries that have effectively disengaged economic growth from carbon emissions?

No, but  I can identidy coutnris that have effectivelengaged economic growth from carbn emissions
"""

df

df.isna().sum()

df.groupby('Value_co2_emissions_kt_by_country')['gdp_growth'].apply(lambda x: x.sort_values(ascending = False))

