# -*- coding: utf-8 -*-
"""Forbes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJamC9h37kkPfYX4228LdXp3kF7zyV-Q
"""

import pandas as pd

forbes=pd.read_csv('https://raw.githubusercontent.com/MrFelipeRE/RE_DataScience/main/Forbes-2021-Global-500-Companies-Statistics.csv')

from google.colab import drive
drive.mount('/content/drive')

forbes

"""1) Make a table with the top 5 companies with the highest Market Value and Assets difference

"""

forbes['difference']=abs( forbes['Market Value $']-forbes['Assets $'])
forbes.sort_values('difference',ascending=False).loc[:,['Name','difference']].head(5)

"""2) Make a list of the company of each country with the highest Assets"""

forbes.sort_values('Assets $',ascending=False).drop_duplicates('Country').loc[:,['Name','Country','Assets $',]].set_index('Name')

"""3) Show a table with the max, min, and ave Market values for each country."""

forbes.groupby('Country')['Profit $'].describe().loc[:,['max','min','mean']]

"""4) Make a list with the top assets reported per country.

"""

forbes.groupby(['Country'])['Assets $'].count().sort_values(ascending=False)

"""5)What are the countries with the highest Sales and  lowest sales?"""

forbes.groupby('Country')['Sales $'].mean().sort_values(ascending=False).iloc[[0,-1]]

"""6)Which company has the lowest assets in the US?"""

forbes[forbes['Country']=='United States'].groupby('Name')['Assets $'].idxmin().sort_values(ascending=False).head(1)

"""7) How many Unites States companies are in top 100 rank?"""

forbes[forbes['Country']=='United States'][forbes['Rank']<100].count().head(1)

"""8) Show a graph including 10 companies with the lowest sales in US"""

forbes[forbes['Country']=='United States'].groupby('Name')['Sales $'].idxmin().sort_values(ascending=False).head(10).plot(kind='bar')

"""9)Create a bar graph showing the top 5 companies with the highest Assets"""

forbes.groupby('Country')['Assets $'].sum().sort_values(ascending=False).head().plot(kind='bar')

"""10) Create a scatter plot comparing profits and sales of US companies"""

forbes[forbes['Country']=='United States'].plot.scatter(x="Sales $", y="Profit $", alpha=0.5)

"""11) What percent of the companies are based in the United States?"""

forbes[forbes['Country']=='United States'].count().head(1)/500*100

"""In the data set by Forbes 2021 Global 500 Companies Statistics, there is data on the sales, profits, assets, and market value of the top 500 companies in the world. When extracting and organizing the information I focused on the United States and discovered that in the top 100 companies in the world 39 of those are based in the US demonstrating America’s dominant role in the global market. Fannie Mae, a US company, has the second largest assets in the world right after China, however, America still holds the #1 spot for assets. The United States' highest market value company is worth 60 trillion, and the average market value is $5 trillion which is huge compared to neighboring countries. While some US companies like Key Corp aren’t as successful as JP Morgan, these companies influence economies, businesses, and individuals in more ways than one. These big corporations in the US make up 34% of the top 500 rank resulting in America having an enormous impact on supply and demand chains, production, consumer satisfaction, anpolicies.

"""