# -*- coding: utf-8 -*-
"""Michael_Wesoloski_Chipotle_orders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CU6FQs38SoFKLUH5LkDLHdyx9WQfiHY
"""

import pandas as pd

orders = pd.read_csv('http://bit.ly/chiporders',sep='\t')

orders

"""1- How many orders are in the dataset over $50?"""

orders['price']=orders['item_price'].str[1:].astype(float)

(orders.groupby('order_id')['price'].sum()>50).sum()

"""2- What is the most popular Item?"""

#orders['item_name'].value_counts().head(1)

(orders.groupby('item_name')['quantity'].sum()).sort_values(ascending=False).head(1)

"""3- What is the item with the highest gross sales?"""

orders.groupby('item_name')['price'].sum().idxmax()

"""my own question: what was the most expensive order and how many items were in it?"""

grouped = orders.groupby(['order_id']).sum().idxmax()
print(grouped)

orders

grouped.max()

"""4- What is the most popular salsa in the dataset?"""

orders['f_desc']=orders['choice_description'].str.split(',',expand=True)[0]
#orders['choice_description']=str(orders['choice_description'])

orders['choice_description'].str.split(',',expand=True)[0].value_counts().head(1)

#orders.groupby(["item_name", "choice_description"])["order_id"].count().reset_index(name="count")

"""5- What is the most popular salsa ordered with Chicken Bowl?"""

orders.loc[orders['item_name'].isin(['Chicken Bowl']),'choice_description'].str.split(',',expand=True)[0].value_counts().head(1)

orders[orders['item_name'].isin(['Chicken Bowl'])].groupby('f_desc')['quantity'].sum().idxmax()[1:]

"""6- What is the most expesive item in the dataset?"""

orders.groupby('item_name')['item_price'].max().sort_values(ascending=False).head(1)

orders.iloc[(orders['price']/orders['quantity']).idxmax()]

"""7- What order has the most items?"""

orders.groupby('order_id')['quantity'].sum().sort_values(ascending=False).head(1)

orders[orders['order_id']==orders.groupby('order_id')['quantity'].sum().idxmax()]

"""8- Create a column with the order price."""

orders['order_price']= orders.groupby('order_id')['price'].sum()

"""9- Create a boolean column that is true if the description contains a fruit."""



"""***OWN QUESTION
What is the most expesive item in the dataset?
"""

orders.iloc[(orders['price']/orders['quantity']).idxmin()]

"""10- Find the price or your own order."""

makeorder = dict(zip(orders.drop_duplicates('item_name')['item_name'],orders.drop_duplicates('item_name')['item_price']))

pd.Series(['Steak Burrito','Chips']).map('makeorder')

orders.to_csv('/content/drive/MyDrive/Applied Data Science/chiptole.csv')

from google.colab import drive
drive.mount('/content/drive')