# -*- coding: utf-8 -*-
"""Superstore_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yrs3ZTJ1EBXOMndqWz25Nl9macZ88yV3
"""

import pandas as pd

sales = pd.read_csv('https://raw.githubusercontent.com/MrFelipeRE/RE_DataScience/main/superstore.csv')

sales.head()

"""Most popular item sub category= binder"""

sales.groupby('Sub-Category')['Sales'].count().sort_values(ascending=False)

"""Most popular item category= OFFICE SUPPLIES"""

sales.groupby('Category')['Sales'].count().sort_values(ascending=False)

"""What price of item sells the most on average at its price= eldon 14.76"""

sales.groupby('Product Name')['Sales'].value_counts().sort_values(ascending=False).index[0]

sales.groupby('Product Name')['Sales'].value_counts().plot.barh(stacked=True);

"""(client retention rate) What are the average number of items per consumer"""

sales.groupby('Customer ID').count().mean()

sales.groupby('Customer ID').count().plot.bar

"""(client retention rate) What are the average number of orders per consumer"""

sales.groupby('Order ID').count().mean()

"""Most popular sub category by sales"""

sales.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False).plot.barh(stacked=True);

sales.groupby('Category')[].sum().sort_values(ascending=False).plot.barh(stacked=True);

