# -*- coding: utf-8 -*-
"""Tech_Layoffs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1Y7K8uqwn5iqQlASakT6N7ubgHk54hq
"""

import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/2025 - 2026/Independent Studies/Data Analysis/Tech Layoffs/tech_layoffs.xlsx')

from google.colab import drive
drive.mount('/content/drive')

df

copy_df = df.copy()

copy_df['total_layoffs'] = copy_df['total_layoffs'].str.replace('\D', '0', regex=True).astype(int)
copy_df['impacted_workforce_percentage'] = copy_df['impacted_workforce_percentage'].str.replace('\D', '0', regex=True).astype(int)

copy_df

import matplotlib.pyplot as plt
import seaborn as sns

top_10 = copy_df.sort_values('total_layoffs',ascending=False).head(10)

fig, ax = plt.subplots(figsize=(25, 10))
p=sns.barplot(x="total_layoffs", y="company", data=top_10,
              ax=ax)
plt.title("Top 10 Layoff Companies")
plt.xlabel('Layoffs')
plt.ylabel('Name')
plt.show()

company_layoffs = copy_df.groupby("company")["total_layoffs"].sum().sort_values(ascending=False).head(5)

company_layoffs

top_10 = copy_df.sort_values('impacted_workforce_percentage',ascending=False).head(10)

fig, ax = plt.subplots(figsize=(25, 10))
p=sns.barplot(x="impacted_workforce_percentage", y="company", data=top_10,
              ax=ax)
plt.title("Top 10 Layoff Companies")
plt.xlabel('Impacted Workforce Percentage')
plt.ylabel('Name')
plt.show()

cut_100 = copy_df.copy()
cut_100.loc[cut_100['impacted_workforce_percentage'] != 100]
cut_100 = cut_100[cut_100.impacted_workforce_percentage != 100]
top_10 = cut_100.sort_values('impacted_workforce_percentage',ascending=False).head(10)
top_10

copy_df['total_layoffs'].sum()

print(df['industry'].value_counts())

print('Distribution of reported dates:')
print(df['reported_date'].value_counts())

top_10 = cut_100.sort_values('impacted_workforce_percentage',ascending=False).head(10)

fig, ax = plt.subplots(figsize=(25, 10))
p=sns.barplot(x="impacted_workforce_percentage", y="company", data=top_10,
              ax=ax)
plt.title("Top 10 Layoff Companies")
plt.xlabel('Impacted Workforce Percentage')
plt.ylabel('Name')
plt.show()

df.groupby('headquarter_location')['total_layoffs'].count().sort_values(ascending=False).head(5)

df.groupby('headquarter_location')['total_layoffs'].count().sort_values(ascending=False).head(5).plot(kind="bar")

industry_copy = df.copy()

ind = []
for i in industry_copy['industry'].to_list():
    ind.append(i.split(' ')[-1])

ind = [x.lower() for x in ind]
ind = [x.replace("-", "") for x in ind]

industry_copy['industry'] = ind

industry_copy

industry_counter = industry_copy.groupby("industry")["total_layoffs"].count().sort_values(ascending=False)

industry_counter

colors = sns.color_palette('pastel')[0:5]

labels = labels = industry_counter.index

#create pie chart
plt.pie(industry_counter, labels = labels, colors = colors, autopct='%.0f%%')
plt.show()

